name: ci

on:
    push:
        branches: [ master ]

jobs:
    macos:
        runs-on: ${{ matrix.runner }}
        strategy:
            matrix:
                runner:
                    - macos-11
                    - macos-12
                    - macos-13
                arch:
                    - x86_64
                    - arm64
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    submodules: recursive
            -   name: Build
                run: |
                    ./build.sh
